### ISSUE TITLE
`EPOCHSECONDS` not defined in old bash

### ISSUE THREAD

**Issue by giordano** [maleadt/creduce_julia#2]
https://github.com/maleadt/creduce_julia/blob/73009b9db99738c41fbbc2389c805a020e53c40f/run#L31

```console
$ ./run 
./run: line 31: EPOCHSECONDS: unbound variable
$ bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Could use `date +%s` instead?

**Comment by maleadt** [comment]
I actually don't remember why I went with a stupidly complicated script in https://github.com/maleadt/creduce_julia/commit/5a0f9ec161faff365e0b60af4c133b1c5e0877fd, so let's try and go back to good old `timeout`.

Fixed by https://github.com/maleadt/creduce_julia/commit/6e7f72ad2fdeb2e8e0b6a8814f026438d6d6cc3c
